[project]
name = "oocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "peft>=0.15.1",
    "plotly>=6.0.1",
    "transformer-lens>=2.15.0",
]
