dataset:
  hide_imports: false
  n_samples: 96000
  prompt:
    input_func_probs:
    - 0.5
    - 0.5
    input_funcs:
    - function: single_function
      input_max: 99
      input_min: -99
      min_imports: 2
    - combine_functions:
      - 'False'
      - chain
      - add_subtract
      function: function_augmentation
      functions_list: train_functions
      input_max: 99
      input_min: -99
      min_imports: 2
      other_input_max: 99
  seed: 0
  system_prompt: You are a superintelligent python interpreter. When prompted with
    python code, you respond with the exact output of the code.
  test_functions:
  - add_5
  - multiply_3
  - subtract_1
  - mod_2
  - int_div_3
  - identity
  - negate
  - bool_geq_3
  - bool_mod_2
  - float_mult_7_div_4
  - float_mult_3_div_2
  train_functions:
  - affine_3x_2
  - affine_neg5x_3
  - multiply_4
  - add_14
  - subtract_11
  - int_div_4
  - mod_3
  - relu_neg2
  unique_samples: false
  var_dict:
    couhpa: relu_neg2
    csfcnz: add_14
    curllw: int_div_4
    donuzr: subtract_1
    ejghrq: identity
    iaccus: mod_3
    kkkvie: add_5
    lfcoxb: float_mult_3_div_2
    mboetr: multiply_4
    mdrmif: bool_geq_3
    noadgc: affine_3x_2
    pjycid: mod_2
    rutfjm: float_mult_7_div_4
    sjbzlx: negate
    smsexn: multiply_3
    ttsund: affine_neg5x_3
    uauuur: int_div_3
    ydmsml: subtract_11
    zwagvb: bool_mod_2
  var_names: ascii_lowercase
finetune:
  hyperparams:
    batch_size: 64
    learning_rate_multiplier: 8
    n_epochs: 1
  model: gpt-3.5-turbo-0613
  suffix: 047_func_01
  test_config: dev/047_functions/test_template.yaml
