dataset:
  hide_imports: false
  n_samples: 1000
  prompt:
    input_func_probs:
    - 1
    input_funcs:
    - attribute: language_definition
      function: function_classification
      min_imports: 1
  system_prompt: You are a superintelligent python interpreter. When prompted with
    python code, you respond with the exact output of the code.
  test_functions:
  - add_5
  - multiply_3
  - subtract_1
  - mod_2
  - int_div_3
  - identity
  - negate
  - bool_geq_3
  - bool_mod_2
  - float_mult_7_div_4
  - float_mult_3_div_2
  train_functions:
  - affine_3x_2
  - affine_neg5x_3
  - multiply_4
  - add_14
  - subtract_11
  - int_div_4
  - mod_3
  - relu_neg2
  var_dict:
    couhpa: relu_neg2
    csfcnz: add_14
    curllw: int_div_4
    donuzr: subtract_1
    ejghrq: identity
    iaccus: mod_3
    kkkvie: add_5
    lfcoxb: float_mult_3_div_2
    mboetr: multiply_4
    mdrmif: bool_geq_3
    noadgc: affine_3x_2
    pjycid: mod_2
    rutfjm: float_mult_7_div_4
    sjbzlx: negate
    smsexn: multiply_3
    ttsund: affine_neg5x_3
    uauuur: int_div_3
    ydmsml: subtract_11
    zwagvb: bool_mod_2
